trigger:
- main

pool:
  vmImage: 'macOS-latest'

steps:
- checkout: self
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.6'
    addToPath: true

- script: |
    gem install fastlane
    fastlane your_lane
  displayName: 'Run Fastlane'
  env:
    APP_STORE_CONNECT_KEY_ID: $(apple-key-id)
    APP_STORE_CONNECT_ISSUER_ID: $(apple-issuer-id)
    APP_STORE_CONNECT_KEY: $(apple-api-key)
